name: apple_gadget_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  # Sate Management
  get_cli: ^1.8.4
  get: 4.6.6

  # Local Database
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2

  # Network
  http: ^1.2.0


  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

dependency_overrides:
  http: ^0.13.5

flutter: 
  uses-material-design: true

  assets:
    - assets/images/